### ISSUE TITLE
WS2813 wiring/usage

### ISSUE THREAD

**Issue by lifebarier** [pimoroni/rpi_ws281x-python#100]
In script updated led count to my 144.
Tried wiring only DI and leaving BI not connected, and tries wiring both to to same pin.
Tried connecting to pin 18 and to spi.

In both cases result is same - strip is blinking like crazy but seemingly randomly.

Any advice?

**Comment by lifebarier** [comment]
Ok, 220ohm resistor on DIN did the trick.
This needs to be documented better somewhere.

**Comment by Gadgetoid** [comment]
Thanks for volunteering 😆
