### ISSUE TITLE
On a 100-LED 1 meter long LED strip, how to address LEDs 25-75?

### ISSUE THREAD

**Issue by MainzerKaiser** [pimoroni/rpi_ws281x-python#75]
Hi all,
I adopted the colorwipe function and instead of going in the range(strip.numPixels()):

```
def colorWipe(strip, color, wait_ms=50):
    for i in range(strip.numPixels()):
        strip.setPixelColor(i, color)
        strip.show()
        time.sleep(wait_ms/1000.0)
```

... I would like to use the middle N LEDs, e.g. 25-75 if N=50 is chosen. But something like that
```
def colorWipe(strip, color, wait_ms=50):
    for i in range(25,75,1):
        strip.setPixelColor(i, color)
        strip.show()
        time.sleep(wait_ms/1000.0)
```
only works up to LED No. 50 and the rest does not react. However, running the original code with 75 LEDs results in the the colorwipe also running from LED 1 to LED 75.
Why is that?

**Comment by Gadgetoid** [comment]
There's no reason why this should be the case, afaik, try v5.0.0 and see if it helps.
