### ISSUE TITLE
Does this library work with the pico MC?

### ISSUE THREAD

**Issue by MainzerKaiser** [pimoroni/rpi_ws281x-python#76]
Hi all,
I tested the library using the gpio interface on an extension mounted to a breadboard. 
Does it work to call a pico micro controller?

**Comment by Gadgetoid** [comment]
An RP2040? This library wraps a C extension that's *extremely specific* to just the Raspberry Pi single-board computer lineup. It wont even begin to work on anything else.

There are "neopixel" libraries for CircuitPython and also MicroPython and WS2812 pixels can be trivially driven with PIO for C++ as demonstrated here: https://github.com/raspberrypi/pico-examples/tree/master/pio/ws2812
