### ISSUE TITLE
No support for 1gb rev 03115

### ISSUE THREAD

**Issue by michaelacosta-rpi** [pimoroni/rpi_ws281x-python#84]
Hardware revision not supported error

Raspberry Pi 4 1gb 0xa03115

**Comment by Gadgetoid** [comment]
Looks like that's inbound in https://github.com/jgarff/rpi_ws281x/pull/496

**Comment by marcuszerep** [comment]
Same issue as https://github.com/rpi-ws281x/rpi-ws281x-python/issues/86

**Comment by Gadgetoid** [comment]
This should have been added in 4.3.4
