### ISSUE TITLE
unable to build setup.py

### ISSUE THREAD

**Issue by kylerobert425** [pimoroni/rpi_ws281x-python#85]
Getting the following error when I go to build the setup: 

running build
running build_py
Compiling ws281x library...
creating build
creating build/lib.linux-armv7l-3.9
creating build/lib.linux-armv7l-3.9/rpi_ws281x
copying rpi_ws281x/rpi_ws281x.py -> build/lib.linux-armv7l-3.9/rpi_ws281x
copying rpi_ws281x/__init__.py -> build/lib.linux-armv7l-3.9/rpi_ws281x
running build_ext
building '_rpi_ws281x' extension
creating build/temp.linux-armv7l-3.9
creating build/temp.linux-armv7l-3.9/lib
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include/python3.9 -c lib/dma.c -o build/temp.linux-armv7l-3.9/lib/dma.o
arm-linux-gnueabihf-gcc: error: lib/dma.c: No such file or directory
arm-linux-gnueabihf-gcc: fatal error: no input files
compilation terminated.
error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1

any ideas on how to fix this?

**Comment by Gadgetoid** [comment]
Did you `git submodule update --init` IE: is there anything at all in the `lib` dir?
