### ISSUE TITLE
Can't access RPi PWM0, without overwriting PWM1

### ISSUE THREAD

**Issue by NeusAap** [pimoroni/rpi_ws281x-python#87]
Hello, 

I know there are already issues that come close to this issue. Still, I'd like to start a new discussion, to figure this problem out together.

My issue is that, when I use this library with PWM channel 0, it seems to screw over PWM channel 1. (on a `Raspberry Pi Compute Module 4 (8GB eMMC, 4GB RAM, No Wifi)`).

I am using the `rpi-ws281x-python` lib to control PWM channel 0, and using `rpi-hardware-pwm 0.1.4` to control PWM channel 1.

The `rpi-hardware-pwm 0.1.4` lib, reads and writes to the PWM buffers directly. (So in my case, in `/sys/class/pwm/pwmchip0/pwm1`)

This seems to work perfectly, if I run my test application before starting `rpi-ws281x-python` application. My oscilloscope shows me the expected PWM signal. After I start the `rpi-ws281x-python` application, the PWM signal on channel one, starts oscillating between 0 and 3.3v very rapidly. 

So my guess is, that the `rpi-ws281x-python` library seems to always initialize BOTH PWM channels. I looked at the source code, and yeah. There is quite a lot of code that mentions PWM channel 1, even when only PWM channel 0 is selected. So I decided to change the library, and remove all mentions off PWM 1. I also added in a couple of printf() calls, to check if channel 1 is never called. 

I am no hero in C, so it could be that I am missing some references here. After removing all references to channel 1, the library still seems to work on channel 0 as expected. But it still messes with channel 1. My next theory is that I am missing some other assignments, so that channel 1 is still overriden in some way. Maybe a DMA call that reserves memory for channel 1, or something alike? 

If someone finds a clue to solve this problem, I would be glad to test it out. 

I have uploaded my source files and binaries here (I mostly edited `ws2811.c`, `ws2811.h`, `pwm.c`, `pwm.h` and  `rpi_ws281x/rpi_ws281x.py`):
[rpi-ws281x-python_NeusAapBuild_v6.zip](https://github.com/rpi-ws281x/rpi-ws281x-python/files/9020949/rpi-ws281x-python_NeusAapBuild_v6.zip)

Any help would be greatly appreciated, since I can't think of any other fixes to try :)

Thanks in advance!
Mats de Waard

P.S, If anybody knows a library that can control PWM1 in combination with `rpi-ws281x-python` being in control of PWM 0, that would also be a great solution. I am a bit too deep into my application to find a replacement for `rpi-ws281x-python`. But I would survive if I'd have to change out the `rpi-hardware-pwm 0.1.4` lib. I've seen the `RPi.GPIO` lib being mentioned as a 'workaround', but this lib uses software PWM. My use case requires a cleaner, more precise hardware PWM signal.

**Comment by Gadgetoid** [comment]
Issues with the underlying rpi_ws281x (https://github.com/jgarff/rpi_ws281x/) are outside the scope of this wrapper library and cannot be fixed here.
