### ISSUE TITLE
rpi-ws281x-python examples do not work

### ISSUE THREAD

**Issue by HaZZar-Oce** [pimoroni/rpi_ws281x-python#88]
strandtest.py fails with this error
ImportError: No module named rpi_ws281x

Trying to run setup.py fails with 
ImportError: No module named setuptools

I started with the error of -3 hardware revision failed and have tried fresh intsalling everything to get nowhere.

trying to run using python2.7 as I am trying to get it to work on my new RPI4 8Gb Rev 1.5 64bit os using code from a RPI0W

**Comment by Apapora** [comment]
>     strandtest.py fails with this error
>     ImportError: No module named rpi_ws281x
You need to install the rpi_ws281x module first:
`pip install rpi_ws281x`

Then run strandtest.py:
`python strandtest.py`
