### ISSUE TITLE
Pros and cons of using this library versus Adafruit_CircuitPython_NeoPixel?

### ISSUE THREAD

**Issue by dasl-** [pimoroni/rpi_ws281x-python#89]
Hi there. I'm working on a project for controlling ws2812b LEDs from a raspberry pi 4. I'm wondering what the pros and cons are of using various driver libraries:

1. https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel 
2. https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel_SPI
3. https://github.com/rpi-ws281x/rpi-ws281x-python

In case it's relevant, I'll be controlling approximately 600 ws2812b LEDs with a desired frame rate of 30 FPS. I will want the pi to have audio output simultaneously. I will be using python.

Thanks for any insight you can provide, although I understand that asking about other libraries may be outside the scope of your knowledge!

**Comment by Gadgetoid** [comment]
AFAIK any other Pi-based library is just a wrapper around this one. NeoPixel/Blinka certainly is-  https://github.com/adafruit/Adafruit_Blinka/blob/b84de4800b2c31023f29a536d26209bd7517d504/src/adafruit_blinka/microcontroller/bcm283x/neopixel.py#L7

I don't know what the SPI library does.

**Comment by dasl-** [comment]
Thanks!
