### ISSUE TITLE
swig/python detected a memory leak of type 'ws2811_t *', no destructor found

### ISSUE THREAD

**Issue by GuyPerets106** [pimoroni/rpi_ws281x-python#96]
Hi , I'm working on a CM4 + IO Board. 
Model: Raspberry Pi Comput Model 4 Rev 1.1
Revision: d03141

The file 'lowlevel.py' in the examples folder is working fine, and also 'SK6812_lowlevel.py', but my own code using PixelStrip is not working. I also checked the strandtest.py file that uses the same class and it didn't work either.
The error I keep getting is:
`Traceback (most recent call last):`
  `File "/home/pi/rpi-ws281x-python/examples/SK6812_strandtest.py", line 89, in <module>`
    `strip = PixelStrip(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL, LED_STRIP)`
  `File "/usr/local/lib/python3.9/dist-packages/rpi_ws281x/rpi_ws281x.py", line 59, in __init__
    super(PixelStrip, self).__init__(self._channel, num)`
`TypeError: object.__init__() takes exactly one argument (the instance to initialize)`
`swig/python detected a memory leak of type 'ws2811_t *', no destructor found.`

There's a way of fixing that problem? it occurred after I had another problem regarding `Hardware revision not supported` but I fixed it using the method in https://github.com/jgarff/rpi_ws281x/issues/483 and then this problem started happening.

**Comment by Gadgetoid** [comment]
Are you running v5.0.0 from https://github.com/rpi-ws281x/rpi-ws281x-python/pull/92?

You can try installing it from https://test.pypi.org/project/rpi-ws281x/

**Comment by GuyPerets106** [comment]
> Are you running v5.0.0 from #92?
> 
> You can try installing it from https://test.pypi.org/project/rpi-ws281x/

I was on 4.3.4 and updated it now to 5.0.0, It worked! Thank you!

**Comment by Gadgetoid** [comment]
That's good news. I suppose I should properly release v5.0.0 then!
